---
cluster_admin_list:
  - fx-emergency

projecttemplate:
  enabled: true

generic-cluster-config:  
  ############################
  # DISABLE SELF PROVISIONER #
  ############################
  self_provisioner:
    deactivate: true
  
  ######################
  # IDENTITY PROVIDERS #
  ######################
  idp:
    enabled: true
    # Define provider. Currently htpasswd and LDAP are supported
    providers:
      enabled: true
      htpasswd:
        - name: HTPASSWD
          enabled: true
          secretname: htpasswd-secret

  ##############
  # MONITORING #
  ##############
  monitoring:
    enabled: true
    enableUserWorkload: true
  
    ################
    # ALERTMANAGER #
    ################
    # Configuration for the cluster (main) Alertmanager
    alertmanagerMain:
      disable_local_alertmanager: false
  
      # Add storage to Alertmanager to keep the data.
      storage:
        class: gp3-csi
        size: 2Gi
  
    ##############
    # PROMETHEUS #
    ##############
    prometheusK8s:
  
      retention: 2d
  
      # Add storage to Prometheus to keep the data.
      storage:
        class: gp3-csi
        size: 10Gi
