---
nodes:
  - name: node1
    enabled: true
    ignore_argocd_labels: true

    custom_labels:
      environment: 'Management'

    roles:
      infra: true
      worker: true

    spec:
      taints:
      - effect: NoSchedule
        key: infra
        value: reserved
