---

# Install Operator Compliance Operator
# Deploys Operator --> Subscription and Operatorgroup
# Syncwave: 0
helper-operator:
  operators:
    compliance-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: cert-manager-operator
        create: true
      subscription:
        channel: stable-v1
        approval: Automatic
        operatorName: openshift-cert-manager-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: false

helper-status-checker:
  enabled: true

  checks:
    - operatorName: cert-manager-operator
      namespace:
        name: cert-manager-operator
      serviceAccount:
        name: "status-checker-cert-manager"

clusterManager:
  enable_patch: true

  overrideArgs:
    - '--dns01-recursive-nameservers-only'
    - --dns01-recursive-nameservers=ns-362.awsdns-45.com:53,ns-930.awsdns-52.net:53

clusterIssuer:
  - name: letsencrypt-prod
    enabled: true
    syncwave: 20

    acme:
      email: tjungbau@redhat.com

      solvers:
        - dns01:
            route53:
              accessKeyIDSecretRef:
                key: access-key-id
                name: prod-route53-credentials-secret
              region: us-west-1
              secretAccessKeySecretRef:
                key: secret-access-key
                name: prod-route53-credentials-secret
          selector:
            dnsZones:
              - aws.ispworld.at

  - name: selfsigned
    enabled: true
    selfSigned: true

  - name: ca
    enabled: true
    ca:
      secretName: ca-key-pair

  - name: vault
    enabled: true
    vault:
      path: pki_int/sign/example-dot-com
      server: https://vault.local
      caBundle: <base64 encoded caBundle PEM file>
      auth:
        tokenSecretRef:
          name: cert-manager-vault-token
          key: token

  - name: venafi
    enabled: true

    venafi:
      zone: "My Application\\My CIT"
      cloud:
        apiTokenSecretRef:
          name: vaas-secret
          key: apikey
