apiVersion: v2
name: setup-container-security-operator
description: Setup the Quay Container Security Operator.
version: 1.0.6
dependencies:
  - name: helper-operator
    version: ~1.0.14
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
keywords:
  - acs
  - security
