---
helper-operator:
  operators:
    security-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-operators
        create: false
      subscription:
        channel: stable-3.11
        approval: Automatic
        operatorName: container-security-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: false
        notownnamespace: true

helper-status-checker:
  enabled: true

  checks:

    - operatorName: container-security-operator
      namespace:
        name: openshift-operators
      syncwave: 3

      serviceAccount:
        name: "status-security-operator"
