---
apiVersion: v2
name: clusterconfig-apiserver
description: Enables ETCD encryption, customer certificate and audit-profile for APIServer
version: 1.0.2
dependencies:
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
  - name: generic-cluster-config
    version: ~1.0.10
    repository: https://charts.stderr.at
  - name: cert-manager
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: cert-manager.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
home: https://github.com/tjungbauer/openshift-clusterconfig-gitops/tree/main/clusters/all/etcd-encryption
keywords:
  - security
