---
# -- Using subchart generic-cluster-config
generic-cluster-config:
  apiserver:
    enabled: true
  
    # audit configuration
    audit:
      profile: Default
  
    # Configure a custom certificate for the API server
    custom_cert:
      enabled: false
  
      cert_names:
        - api.ocp.aws.ispworld.at
  
      secretname: api-certificate
  
    etcd_encryption:
      enabled: true
      encryption_type: aesgcm
  
      # -- Namespace where Job is executed that verifies the status of the encryption
      namespace: kube-system
  
      serviceAccount:
        create: true
        name: "etcd-encryption-checker"


      encryption_type: aesgcm