ep: &endpoint sonarqube.apps.ocp.aws.ispworld.at

namespace:
  # -- Namespace where Sonarqube shall be deployed
  name: sonarqube

  # -- Shall the namespace be created?
  # @default -- false
  create: true

# -- Start a Job to set an initial password
# @default -- false
set_admin_password: true

# -- Endpoint so that the Job that is configuring the initial password can connect.
endpoint: *endpoint

# -- Sonarqube Settings
# These settings are defined by Sonarqube Helm chart.
sonarqube:
  fullnameOverride: sonarqube

  OpenShift:
    # -- OpenShift should be enabled
    enabled: true
    # -- The SCC should be created for OpenShift deployment.
    createSCC: true
  # -- Keep the data persistent
  persistence:
    enabled: true
  # -- Enable Network Polocies ... maybe I should set this to true
  networkPolicy:
    enabled: false

  # -- Enable ingress, using the defind endpoint.
  route:
    enabled: true
    host: *endpoint
    tls: edge


  # -- additional plugins to install
  plugins:
    install:
      - https://github.com/checkstyle/sonar-checkstyle/releases/download/10.9.3/checkstyle-sonar-plugin-10.9.3.jar
      - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/3.1.0/sonar-dependency-check-plugin-3.1.0.jar
      - https://github.com/sbaudoin/sonar-yaml/releases/download/v1.7.0/sonar-yaml-plugin-1.7.0.jar
      - https://github.com/sbaudoin/sonar-shellcheck/releases/download/v2.5.0/sonar-shellcheck-plugin-2.5.0.jar
     # - https://github.com/SonarQubeCommunity/sonar-l10n-de/releases/download/1.2/sonar-l10n-de-plugin-1.2.jar
