---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgCiXpZ1TIjBKGh4ihyd2yxq2dxaMQ4yGpUrMQIJUGoImapTmY6G0T157a7a3V+OA34DcbS/LeGMUCc1d2lRBBSOPc8S0Qu0hUJx2gkAfYJckX2bZYI03EyuvKf/TX30vMCKJe3O1inQRxrV2e54IfMkIduPEYADNwAmJGPSafbYb9ZdZkOp4lydK6nCvnPzAa7J0gWlJa+EGdzNmDBnjiiwo9rrksrNQ9Pok7i4ZnmoaEF2nYpqEFVUGZH5124OcKmZO+r5PPoRxC9hq2wORYdZRAR50GpPDUPqHwf1fq8d6O5HcW7wJXvcQpuPUZ8znsEh0xQ+PfpR2ZJ0CquvCt/l1pR2JYj4X3s0bZEEaVK6bp5Pum2osXm+ZmYUxxfR9/p5KgLpg7nzPMd7IYtw6It4S/jK1oUVqiz30Ctkxe3F+tVEOYXlHWyMxiXaiVozazAKxyDc19FithYR62WJcGGzmGxUMRQUJJuCohHOYuOFZGxxouS0tmnzkLNKs2hVkl9M8cZbk2rHB6Szbq+OzB+9kRxtWrCgbnhRQ3vW9YMIeXgmr7mCaFGxmnyzHRA0PteOBwazzO+BQXOKhZf4GO81ml+jnI+LL8MSwxPfw7ycaY3oIo+lR7UBggRYE2GYyjL7KIDlE8oIOKYx3eVN3Q4W9Stn9x00vghZz2vJZb66CnZ0TPh4CNY2HG1FlMsH1ZInREXqA1S8YA4q4UPZJZ4neWZSJQWuQeYaRPJod+TxFg2zR+xRMmNnSUfcAxkdK1xSEjy3j5VM7uDDTbwR2lGx04FMRAyYr354emaJWZlbayp8sf9j5OzDSJfxRJn0OI3nGrROXDPJmtDZRfr1silhY9+UTY7H+PPFLQLA89jds+SarncGIa7F2XE2Dd42qKki2h0rTHNu3xMtWrO50XYI31knb78D/Xzdu+X8ngK+EETT
  template:
    metadata:
      name: htpasswd-secret
      namespace: openshift-config