---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBs/Whlr+L9y2ojBlXR+Vsom86wRbZe3HfIN8WOIr4lOqs3olwHyN74QUkzKvPQ+TIlu905J/DqJ5narzxDXWtAxm/I5pFkUgTNR1kL6N53noXiuiYrrh+tKB01FUMhlypenDNPRY5u5gbZ10yWLK31rb1vrF32mfhcacy0Xn1Y8mELuFaGFKSoKvzJDWpMTHzQuTYYQAdkajv/LbEOJ8f18kSGjvbIpJYePYWbCQS7NwibPsCtfk0FfdSp8D2VtDRxJgwWMpfjacfu1zei9SsGrLKKKrhtowH6wqNJmZQNxCvIIeXCCKtUBKNNYb0RajFnqwA2+5ZxlZ+t5wRR/+1dhKkMaoHLDwkbIkfIuqP76nlwqDlqQALH+XC5LYiPiXgIy7iCM7J8wWVhSoMREzwyG9OotyOjFPKUN22xzvktSPbaqFuBAzQ0JdNnR7HVtiBWDrJS2YBXRL3u1y9FFT9fajqgzyxBTwGgUUOKfUpjfmxhOpqpumNqWl+g0/QCN0xPmOb9pxJwopZ60K0z4O7Um1RSH5eRbebmOF01W2xm33ZTnC3SL7ZyqGwoafiHrxslrHb18UrHRlzVq2nf9VV6LmcZg3eipdpdn2TvrM1Vtpo1hvhd1qfs+8lCQchJwdz/YS0WFOexeBJ5I65hOxD2gBCaIYLl14sSdu+9GsVx3xz2lioy97v86mQ31GXmlp3qQNu2tG9DM0FMPXBoJQu0TZKiSoJPFsyOmL8LrHdKY0Q9Jas01PeT4KvQZuw/ZWReNjgunWrQE3xECZerSq79nms+kF9NyRZlkQKnbsjvMx0j1dslBjcbOfxrob7xlxJ3+82kd/NuAOukCNw0IZ2IOYLMuDGzlOKchEEJnn9+82bnsB6HIN/FlcXXgulgM0PJElAXgp3junFlfe3i/HBI+esA8t0NsaRZo7BmhNsCZaiT
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd-secret
      namespace: openshift-config
    type: Opaque