---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name | default "argocd-resources-manager" }}
  namespace: {{ .Values.namespace | default "openshift-gitops" }}
  labels:
    gitops.ownedBy: cluster-config
{{ include "common.labels" . | indent 4 }}
spec:
  destination:
    namespace: {{ .Values.destinationNamespace | default "openshift-gitops" }}
    server: {{ .Values.server }}
  project: {{ .Values.argocd_project }}
  sources:
    - repoURL: {{ .Values.repourl_configuration }}
      targetRevision: {{ .Values.revision_configuration }}
      ref: values
    - repoURL: {{ .Values.repoURL_chart }}
      chart: {{ .Values.chart_name }}
      targetRevision: {{ .Values.chart_version }}
      helm:
        valueFiles:
          {{- range .Values.path_configurations }}
          - $values/{{ . }}
          {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  info:
    - name: Description
      value: 'This is the starting point which will initialize all applicationsets or argocd applications'
