apiVersion: v2
name: setup-crunchy-postgres
description: Deploy and configure Crunchy Postgres Operator and Postgres clusters
home: https://github.com/tjungbauer/openshift-clusterconfig-gitops/tree/main/clusters/management-cluster/setup-crunchy-postgres
version: 1.0.0
dependencies:
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
  - name: helper-operator
    version: ~1.0.21
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
  - name: helper-objectstore
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: helper-objectstore.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - crunchy
  - database
