{{ if eq (.Values.keycloak.enabled | toString) "true" }}
{{ range .Values.keycloak.realms }}
{{ if eq (.enabled | toString) "true" }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.keycloak.namespace.name }}
  labels:
    {{- toYaml .labels | nindent 4 }}
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "10" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      {{- toYaml .labels | nindent 6 }}
  realm:
    displayName: {{ .displayName }}
    enabled: {{ .enabled }}
    id: {{ .id }}
    realm: {{ .realm }}
    sslRequired: {{ .sslRequired }}
{{- end }}
{{- end }}
{{- end }}
