{{ if eq (.Values.keycloak.enabled | toString) "true" }}
{{ range .Values.keycloak.clients }}
{{ if eq (.enabled | toString) "true" }}
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.keycloak.namespace.name }}
  labels:
    {{- toYaml .labels | nindent 4 }}
    {{- include "tpl.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "10" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  client:
    clientAuthenticatorType: {{ .clientAuthenticatorType }}
    redirectUris:
      {{- range .redirectUris }}
      - {{ . | quote }}
      {{- end }}
    serviceAccountsEnabled: {{ .serviceAccountsEnabled }}
    clientId: {{ .clientId }}
    defaultClientScopes:
      {{- range .defaultClientScopes }}
      - {{ . }}
      {{- end }}
    implicitFlowEnabled: {{ .implicitFlowEnabled }}
    publicClient: {{ .publicClient }}
    standardFlowEnabled: {{ .standardFlowEnabled }}
    directAccessGrantsEnabled: {{ .directAccessGrantsEnabled }}
  realmSelector:
    matchLabels:
      {{- toYaml .labels | nindent 6 }}
{{- end }}
{{- end }}
{{- end }}
