{{- if eq ( .Values.netobserv.enabled | toString) "true" }}
{{- with .Values.netobserv }}
---
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .lokistack.name }}
  namespace: {{ .namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .lokistack.syncwave | default "3" | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  size: {{ .lokistack.size | default "1x.extra-small" | quote }}
  storage:
    tls:
      caKey: service-ca.crt
      caName: openshift-service-ca.crt
    {{- if .lokistack.storage.schemas }}
    schemas:
    {{- range .lokistack.storage.schemas  }}
    - version: {{ .version }}
      effectiveDate: {{ .effectiveDate | quote }}
    {{- end }}
    {{- else }}
    schemas:
    - version: v12
      effectiveDate: '2022-06-01'
    {{- end }}
    secret:
      name: {{ .lokistack.storage.secret.name }}
      type: {{ .lokistack.storage.secret.type | default "s3" }}
  storageClassName: {{ .lokistack.storageclassname }}
  tenants:
    mode: {{ .lokistack.mode | default "static" }}
{{- end }}
{{- end }}
