---
cluster_admin_list:
  - emergency
  - tjungbau@redhat.com

# @ignore
generic-cluster-config:
  ######################
  # IDENTITY PROVIDERS #
  ######################
  idp:
    enabled: true
    # Define provider. Currently htpasswd and LDAP are supported
    providers:
      enabled: true
      htpasswd:
        - name: Emergency
          enabled: false
          secretname: htpasswd-secret

      google:
        - name: sso
          enabled: true
          secretname: google-secret
          clientID: '297036956546-il71s971lnqgs5ehrifdel5b3vh4tudb.apps.googleusercontent.com'
          hostedDomain: 'redhat.com'
          mappingMethod: claim
