---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: sonarqube
spec:
  encryptedData:
    adminpass: AgAbvBfCsEVsWL5Yojv/j//RpW6KQFDnBympwyvuqVWhDc5C4vvrWuoQaCPEGOW2tUUVpASjIAwYKOqAXi+UJWduC2kwVtayB/t1mIxhGySuL+F65We8cn1msuHRP3og8rCYsJr3dF0YC9ZF2KPrRWilxjJkepUpkDiP0UKyzgSafOLOHDzUYOOsRV5Tl3wvPrULwloylUClercOGSLy5hNYC6EM7J9X3cs7yCUyw3YuTnk5PdqwoMMRvSxCN6aok9v1tcXGEf+FF6gxGR7Px3P4gBdCr+ZiykUe/E93IUQFoV0a6O/PnqgI2Pb2piHF2469EyB10CPBf1xcyMVAnfo4ncYzTABJWZ0ka47Mow9NLACKMzL72ah5e8SaI9w6bgdz/vlAmrbsbNGwbi4mXmRcE6iOKucqWMCmlk1H4gKADfLIQDggWJD6TVKU6iY8YZB/m2n0sqzpUsOiDrbN6pOr0pW1qeqm2+qnEArlxh2Eb2xv//eZ0X8Mw1UjKin9d32iHkSnXWsgU2hOZmYottoYzjdluFofMpE1KVR22SeRbOfwh0M6udV/VUf9QZ4sCgNM3sLzqQubOR3htJh81QoapAZcYEv9iwW76RVvtXmUDFlUsa9gCv0Nvm/SXY1lg82aTMgpPdjCu9SZP5kAGs6ggTVCx/7j4nlcJpMiT3/QF0oISHfULkwiiEPdbx+FHYkLIapS/bFbtQ==
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: sonarqube
