{{ if eq (.Values.gitops.enabled | toString) "true" }}
{{- range .Values.gitops.integration }}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: {{ .clusterSet }}
  namespace: {{ .namespace }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "10" | quote }}
spec:
  clusterSet: {{ .clusterSet }}
{{- end }}
{{- end }}
