apiVersion: v2
name: install-cyclonedx
description: Install Cyclonedx to store SBOMs
version: 1.0.0
dependencies:
  - name: cyclonedx
    version: ~1.0.0
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
keywords:
  - secure-supply-chain
  - security
