---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBCGmJ+abILqWLkbkk8K+H+0kE9Zp27Mk+6FV0dfpUFx3qUY48mTJ3V+yjSJ+rAiZhiREVyNTa8DBWN0yUcuCTYUFx+OUu9me+lMrxu5jHLx5inkuR0r+GhbGwqUxUHHUzBH64/+Uu4/E+6yevper125fZwcwt6oY52qe5ITkbTCaDncgH/QjYZM3b+Fm0kXihSJ5hjkBm5iiVSnpX1sFcg9DnmqR+f235gQYBdVuaOwa6oGXQ1f1GdLlGU1BmXw+UdEE3JMbMGi197fSNs738+p9ahhFvfUvUTYvNfyPDoKR0t9pZ4hzFjquRp8Poe/2KxVNDzMea5PmZgdZa0Pvk1ZQNNsm/hsiMtQRRTt//wI/LLcjyPAegORrDQ4bFyUHGD3WVG1//du2Gr/pExW1yQQJYGuWEJtRfQdaabdVkU6TbVIoloscgX+SjW8CqeYw58o9IlhrcggQ/Fh9cM0SP4ZqwXPXBSnGO1/Fky6uetO1G+BIQzHkuu2PoUma/jHE7BB6n/Eh1sE2Rw2hbJ11kcFuQmvHPBz7HkV5DVYZBhD+Bo8M1leewfW8FpPlXHRhM3o5Q+FJJ4di2awOsMerll21iDKE7TXBU/xe3iGgvaADLzKc3VuThd4MrdEcJE/+0yToOyNHZYiabYIXPpd/N0f0rGCSaXdu52qwHfMIa9Yupe+cX0XFahB726lDucv2qzK+TA6jsON8AgMbWALl0J4CebZVePLTUJIGJsPqKnV4R0JjJeydfZw4yT99UEhOlUpMhA8M7594ClgJrbbi3frjS51DXnN6lb9KrTuZyLF2pbjg6UEaJZV4d9CHq9jzlbx8gYKMPvXZHlr46nivNwUBJkVK5nCYW6qkj7r7aVlokPoxqaOcxYAyYiMf5bhSAPNSuM78KzEdKQNMsYuSisB5/JG69uULe52KWte+bZGv6B
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd-secret
      namespace: openshift-config
