---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAsYsl+OtXnftXDGuPP37W5BMUKaZnQXKfIQjZt5EHUXy+HOeY3yt3OnREQxVNemO59ERls9ZUG9B0fOhcLUXc7L5gx3OBbvbPeseOAUaudMcrO1rSUrk/8CO+IRHMOURd4O4KkPisycTJxYfuPzKCIWGp80HSzAUQoCcuKFF/8RmSnjUS6bN+9+R2OUwT++9NVnCqXdENFog/mOayBJZtj9lgy+qqYnlIceYQLXIiiSyzKs6vEz3lgjrF89I0h0hVwSktMTGfweIbgwMiqSaaGDxUbptj/ybA3iHZMYboRh2Cbv3MtY21P4qQQUWJOx9CNOfnvi/UT+33U3r0yREN2nO7KiEIp6zm+i6XAM/iHQKlSHu7jPonFGjVPzwyrziHQZte89IXIyJwRUNWNsMv6LKjqOfnDUC02dR9z7R34Rz56BHtrrwwAv5NvYPhX5/OCOrkVEBIbXTLByvX6DbpgbKTTum/9w6M81ttFzjfPmhsM6RqrBkeYGlDRlttTivilx6RUKjCCfuunWPeg7AW67Fm8AZAihVWQrVHj0lIu+wPwuyzp+ZpmVwA5UBvG6pRVBX2KRgiN+9NYw16gz6zBpsBbor1R1z1X9ThnD8WAbukzWeBHPM5YxCu28hu9hYKpOmQVb5QzvHOP70YjpjH3APNlY4vFAnL/f1iCsm1FLv9I8+5J3+etYOUCWBPviFC8BNEFIMZtpibR0IqiA+dYpQvlbS4Etuummaeq0UX52ajSa1HHkJdE6sq4eSbO0klAMCGLnKC/uwZx4ATf/iT3UOZNSteIaJd06zifuwbLvYLlhQ6e243EFW5IzfmroWFCW54k7JjB16kNPh4l6b9ftcm7np9v3fgmtfWWMcjx18KLHpQ8+2ULiXB0kEJilRp+KppTMz+S1WBGR5OKTVk/kPg+tcMhLH5EwP+izSb62cjW
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd-secret
      namespace: openshift-config
