{{- with .Values.quay }}
{{- if eq ( .create_config_secret.enabled | toString) "true" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quay-config
  namespace: quay-enterprise
data:
  {{- with .create_config_secret }}
  quay.cleartext.properties: |
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: {{ .allow_pulls_without_strict_logging | quote | default "false" | trimAll "\"" }}
    AUTHENTICATION_TYPE: {{ .authentication_type | quote | default "Database" | trimAll "\"" }}
    AVATAR_KIND: {{ .avatar_kind | quote | default "local" | trimAll "\"" }}
    BROWSER_API_CALLS_XHR_ONLY: {{ .browser_api_calls_xhr_only | quote | default "false" | trimAll "\"" }}
    CREATE_PRIVATE_REPO_ON_PUSH: {{ .create_private_repo_on_push | quote | default "true" | trimAll "\"" }}
    DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: {{ .default_system_reject_quota_bytes | quote | default "1.073741824e+11" | trimAll "\"" }}
    DEFAULT_TAG_EXPIRATION: {{ .default_tag_expiration | quote | default "2w" | trimAll "\"" }}
    DISTRIBUTED_STORAGE_CONFIG:
        default:
            - RadosGWStorage
            - access_key: PATCH_BUCKET_USER
              bucket_name: PATCH_BUCKET_NAME
              hostname: PATCH_BUCKET_HOST
              is_secure: {{ $.Values.quay.bucket.is_secure | quote | default "true" | trimAll "\"" }}
              port: {{ $.Values.quay.bucket.port | quote | default "443" | trimAll "\"" }}
              secret_key: PATCH_BUCKET_SECRET
              storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
        - default
    USERFILES_LOCATION: default
    ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
    EXTERNAL_TLS_TERMINATION: false
    FEATURE_ACTION_LOG_ROTATION: {{ .feature.action_log_rotation | quote | default "false" | trimAll "\"" }}
    FEATURE_AGGREGATED_LOG_COUNT_RETRIEVAL: {{ .feature.aggregated_log_count_retrieval | quote | default "true" | trimAll "\"" }}
    FEATURE_ANONYMOUS_ACCESS: {{ .feature.anonymous_access | quote | default "true" | trimAll "\"" }}
    FEATURE_APP_SPECIFIC_TOKENS: {{ .feature.app_specific_tokens | quote | default "true" | trimAll "\"" }}
    FEATURE_BITBUCKET_BUILD: {{ .feature.bitbucket_build | quote | default "false" | trimAll "\"" }}
    FEATURE_BLACKLISTED_EMAILS: {{ .feature.blacklisted_emails | quote | default "false" | trimAll "\"" }}
    FEATURE_BUILD_SUPPORT: {{ .feature.build_support | quote | default "false" | trimAll "\"" }}
    FEATURE_CHANGE_TAG_EXPIRATION: {{ .feature.change_tag_expiration | quote | default "true" | trimAll "\"" }}
    FEATURE_DIRECT_LOGIN: {{ .feature.direct_login | quote | default "true" | trimAll "\"" }}
    FEATURE_EXTENDED_REPOSITORY_NAMES: {{ .feature.extended_repository_names | quote | default "true" | trimAll "\"" }}
    FEATURE_FIPS: {{ .feature.fips | quote | default "false" | trimAll "\"" }}
    FEATURE_GARBAGE_COLLECTION: {{ .feature.garbage_collection | quote | default "true" | trimAll "\"" }}
    FEATURE_GENERAL_OCI_SUPPORT: {{ .feature.general_oci_support | quote | default "true" | trimAll "\"" }}
    FEATURE_GITHUB_BUILD: {{ .feature.github_build | quote | default "false" | trimAll "\"" }}
    FEATURE_GITHUB_LOGIN: {{ .feature.github_login | quote | default "false" | trimAll "\"" }}
    FEATURE_GITLAB_BUILD: {{ .feature.gitlab_build | quote | default "false" | trimAll "\"" }}
    FEATURE_GOOGLE_LOGIN: {{ .feature.google_login | quote | default "false" | trimAll "\"" }}
    FEATURE_HELM_OCI_SUPPORT: {{ .feature.helm_oci_support | quote | default "false" | trimAll "\"" }}
    FEATURE_INVITE_ONLY_USER_CREATION: {{ .feature.invite_only_user_creation | quote | default "false" | trimAll "\"" }}
    FEATURE_LIBRARY_SUPPORT: {{ .feature.library_support | quote | default "true" | trimAll "\"" }}
    FEATURE_LOG_EXPORT: {{ .feature.log_export | quote | default "true" | trimAll "\"" }}
    FEATURE_MAILING: {{ .feature.mailing | quote | default "false" | trimAll "\"" }}
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: {{ .feature.nonsuperuser_team_syncing_setup | quote | default "false" | trimAll "\"" }}
    FEATURE_PARTIAL_USER_AUTOCOMPLETE: {{ .feature.partial_user_autocomplete | quote | default "true" | trimAll "\"" }}
    FEATURE_PUBLIC_CATALOG: {{ .feature.public_catalog | quote | default "false" | trimAll "\"" }}
    FEATURE_QUOTA_MANAGEMENT: {{ .feature.quota_management | quote | default "false" | trimAll "\"" }}
    FEATURE_RATE_LIMITS: {{ .feature.rate_limits | quote | default "false" | trimAll "\"" }}
    FEATURE_READER_BUILD_LOGS: {{ .feature.reader_build_logs | quote | default "false" | trimAll "\"" }}
    FEATURE_RECAPTCHA: {{ .feature.recaptcha | quote | default "false" | trimAll "\"" }}
    FEATURE_REPO_MIRROR: {{ .feature.repo_mirror | quote | default "true" | trimAll "\"" }}
    FEATURE_RESTRICTED_V1_PUSH: {{ .feature.restricted_v1_push | quote | default "true" | trimAll "\"" }}
    FEATURE_SECURITY_NOTIFICATIONS: {{ .feature.security_notifications | quote | default "false" | trimAll "\"" }}
    FEATURE_SIGNING: {{ .feature.signing | quote | default "false" | trimAll "\"" }} <<
    FEATURE_STORAGE_REPLICATION: {{ .feature.storage_replication | quote | default "false" | trimAll "\"" }}
    FEATURE_SUPER_USERS: {{ .feature.super_users | quote | default "true" | trimAll "\"" }}
    FEATURE_TEAM_SYNCING: {{ .feature.team_syncing | quote | default "true" | trimAll "\"" }}
    FEATURE_UI_V2: {{ .feature.ui_v2 | quote | default "true" | trimAll "\"" }}
    FEATURE_UI_V2_REPO_SETTINGS: {{ .feature.ui_v2_repo_settings | quote | default "false" | trimAll "\"" }}
    FEATURE_USER_CREATION: {{ .feature.user_creation | quote | default "true" | trimAll "\"" }}
    FEATURE_USER_INITIALIZE: {{ .feature.user_initialize | quote | default "false" | trimAll "\"" }}
    FEATURE_USER_LAST_ACCESSED: {{ .feature.user_last_accessed | quote | default "true" | trimAll "\"" }}
    FEATURE_USER_LOG_ACCESS: {{ .feature.user_log_access | quote | default "false" | trimAll "\"" }}
    FEATURE_USER_METADATA: {{ .feature.user_metadata | quote | default "false" | trimAll "\"" }}
    FEATURE_USER_RENAME: {{ .feature.user_rename | quote | default "false" | trimAll "\"" }}
    FEATURE_USERNAME_CONFIRMATION: {{ .feature.username_confirmation | quote | default "false" | trimAll "\"" }}
    FRESH_LOGIN_TIMEOUT: {{ .fresh_login_timeout | quote | default "5m" | trimAll "\"" }}
    FEATURE_PROXY_STORAGE: {{ .proxy_storage | quote | default "false" | trimAll "\"" }}
    GITHUB_LOGIN_CONFIG: {}
    GITHUB_TRIGGER_CONFIG: {}
    GITLAB_TRIGGER_CONFIG: {}
    GITLAB_TRIGGER_KIND: {}
    GLOBAL_PROMETHEUS_STATS_FREQUENCY: 60
    GOOGLE_LOGIN_CONFIG: {}
    LDAP_ALLOW_INSECURE_FALLBACK: false
    LDAP_EMAIL_ATTR: mail
    LDAP_UID_ATTR: uid
    LDAP_URI: ldap://localhost
    LOG_ARCHIVE_LOCATION: default
    LOGS_MODEL: database
    LOGS_MODEL_CONFIG: {}
    MAIL_DEFAULT_SENDER: support@example.com
    MAIL_PORT: 587
    MAIL_USE_AUTH: false
    MAIL_USE_TLS: true
    MAXIMUM_LAYER_SIZE: {{ .maximum_layer_size | quote | default "20G" | trimAll "\"" }}
    PREFERRED_URL_SCHEME: {{ .preferred_url_scheme | quote | default "http" | trimAll "\"" }}
    QUEUE_WORKER_METRICS_REFRESH_SECONDS: 30
    REGISTRY_STATE: {{ .registry_state | quote | default "normal" | trimAll "\"" }}
    REGISTRY_TITLE: {{ .registry_title | quote | default "Red Hat Quay" | trimAll "\"" }}
    REGISTRY_TITLE_SHORT: {{ .registry_title_short | quote | default "Red Hat Quay" | trimAll "\"" }}
    REPO_MIRROR_INTERVAL: {{ .repo_mirror_interval | quote | default "30" | trimAll "\"" }}
    REPO_MIRROR_ROLLBACK: {{ .repo_mirror_rollback | quote | default "false" | trimAll "\"" }}
    REPO_MIRROR_TLS_VERIFY: {{ .repo_mirror_tls_verify | quote | default "false" | trimAll "\"" }}
    SEARCH_MAX_RESULT_PAGE_COUNT: {{ .search_max_result_page_count | quote | default "10" | trimAll "\"" }}
    SEARCH_RESULTS_PER_PAGE: {{ .search_results_per_page | quote | default "10" | trimAll "\"" }}
    SECRET_KEY: 386de725-b366-4dc1-b30a-93de7e1f15a7
    SESSION_COOKIE_SECURE: {{ .session_cookie_secure | quote | default "false" | trimAll "\"" }}
    SETUP_COMPLETE: true
    {{- if .ssl_protocols }}
    SSL_PROTOCOLS:
    {{- range .ssl_protocols }}
      - {{ . }}
    {{- end }}
    {{- else }}
      - TLSv1.3
    {{- end }}
    SUCCESSIVE_TRIGGER_FAILURE_DISABLE_THRESHOLD: {{ .successive_trigger_failure_disable_threshold | quote | default "100" | trimAll "\"" }}
    SUCCESSIVE_TRIGGER_INTERNAL_ERROR_DISABLE_THRESHOLD: {{ .successive_trigger_internal_error_disable_threshold | quote | default "5" | trimAll "\"" }}
    {{- if .tag_expiration_options }}
    TAG_EXPIRATION_OPTIONS:
    {{- range .tag_expiration_options }}
     - {{ . }}
    {{- end }}
    {{- else }}
    TAG_EXPIRATION_OPTIONS:
      - 0s
      - 1d
      - 1w
      - 2w
      - 4w
    {{- end }}
    TEAM_RESYNC_STALE_TIME: {{ .team_resync_stale_time | quote | default "30m" | trimAll "\"" }}
    SUPER_USERS:
      - {{ $.Values.quay.init_user.username | default "admin" }}
      {{- if .super_user_list }}
      {{- range .super_user_list }}
      - {{ . }}
      {{- end }}
      {{- end }}
    TEAM_SYNC_WORKER_FREQUENCY: 60
    TESTING: false
    USER_RECOVERY_TOKEN_LIFETIME: {{ .user_recovery_token_lifetime | quote | default "30m" | trimAll "\"" }}
    USERFILES_PATH: {{ .userfiles_path | quote | default "userfiles" | trimAll "\"" }}
    V2_PAGINATION_SIZE: {{ .v2_pagination_size | quote | default "50" | trimAll "\"" }}
    {{- end }}
{{- end }}
{{- end }}