{{- if eq ( .Values.quay.enabled | toString) "true" }}
{{- with .Values.quay }}
---
kind: Secret
apiVersion: v1
metadata:
  name: init-user
  namespace: {{ .namespace.name }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  mail: {{ .init_user.mail | default "admin@company.com" | b64enc }}
  username: {{ .init_user.username | default "admin" | b64enc }}
  password: {{ randAlphaNum 16 | b64enc }}
type: Opaque
{{- end }}
{{- end }}