apiVersion: v2
name: openshift-logging-deployment
description: Installs and configures OpenShift Logging by calling the Chart openshift-logging
version: 1.0.0
dependencies:
  - name: helper-objectstore
    version: ~1.0.0
    repository: file://../../../charts/helper-objectstore
    condition: helper-objectstore.enabled
