{{- if eq ( .Values.enabled | toString) "true" }}
{{- with .Values }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-image-registry-crb-{{ .namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 3 | quote }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-image-registry-crb-{{ .namespace }}-clusterrole
subjects:
  - kind: ServiceAccount
    name: create-bucket-secret-sa
    namespace: {{ .namespace }}
{{- end }}
{{- end }}
