apiVersion: v2
name: setup-file-integrity-operator
description: Setup File Integrity Operator
version: 1.0.1
dependencies:
  - name: helper-operator
    version: ~1.0.0
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
  - name: file-integrity-operator
    version: ~1.0.0
    repository: https://charts.stderr.at/
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
