---
target_namespace: &namespace trusted-profile-analyzer
s3_hostname: &s3_hostname s3-openshift-storage.apps.ocp.aws.ispworld.at
storageclassname: &storageclassname tpa-bucket-storage-class
bucketname: &bucketname trusted-profile-analyzer

enabled: true

namespace:
  create: true
  name: *namespace

db:
  use_example_db_sts: true
  example_db_user: testuser
  example_db_pass: thisisonly4testingNOT4prod

#######################################################
# If ODF is used, the Chart helper-objectstore
# is able to create the S3 storage for Quay.
#
# It is a helper chart that simply creates another
# backingstore.
# This is a chart in an early state, and not everything
# can be customized for now.
#
# It will create the objects:
#  - BackingStore
#  - BackingClass
#  - StorageClass

# NOTE: Currently only PV type is supported
#######################################################
helper-objectstore:
  enabled: true
  # syncwave: 1

  # Name of the BackingStore
  backingstore_name: tpa-backingstore
  # Size of the BackingStore
  backingstore_size: 700Gi
  # numOfVolumes: 1
  # type: py-pool

  # The StorageClass the BackingStore is based on
  baseStorageClass: gp3-csi

  # Name of the StorageClass that shall be enabled.
  storageclass_name: *storageclassname

  # Bucket that shall be created
  bucket:
    # -- Shall a new bucket be enabled?
    # @default -- false
    enabled: true

    # -- Name of the bucket that shall be created
    name: *bucketname

    # -- Target Namespace for that bucket.
    namespace: *namespace

    # -- Syncwave for bucketclaim creation. This should be done very early, but it depends on ODF.
    # @default -- 2
    syncwave: 2

    # -- Name of the storageclass for our bucket
    # @default -- openshift-storage.noobaa.io
    storageclass: *storageclassname

redhat-trusted-profile-analyzer:
  appDomain: apps.ocp.aws.ispworld.at

  ingress:
    className: openshift-default
    additionalAnnotations:
      "haproxy.router.openshift.io/timeout": "5m"

  storage:
    type: s3
    region: REGION
    bucket: trusted-profile-analyzer-b58f7115-7076-4595-9194-e8b0c213be38
    endpoint: s3.openshift-storage.svc
    accessKey:
      valueFrom:
        secretKeyRef:
          name: trusted-profile-analyzer
          key: AWS_ACCESS_KEY_ID
    secretKey:
      valueFrom:
        secretKeyRef:
          name: trusted-profile-analyzer
          key: AWS_SECRET_ACCESS_KEY

  database:
    sslMode: require
    host:
      valueFrom:
        secretKeyRef:
          name: postgresql-credentials
          key: db.host
    port:
      valueFrom:
        secretKeyRef:
          name: postgresql-credentials
          key: db.port
    name:
      valueFrom:
        secretKeyRef:
          name: postgresql-credentials
          key: db.name
    username:
      valueFrom:
        secretKeyRef:
          name: postgresql-credentials
          key: db.user
    password:
      valueFrom:
        secretKeyRef:
          name: postgresql-credentials
          key: db.password

  createDatabase:
    name:
      valueFrom:
        secretKeyRef:
          name: postgresql-admin-credentials
          key: db.name
    username:
      valueFrom:
        secretKeyRef:
          name: postgresql-admin-credentials
          key: db.user
    password:
      valueFrom:
        secretKeyRef:
          name: postgresql-admin-credentials
          key: db.password

  migrateDatabase:
    username:
      valueFrom:
        secretKeyRef:
          name: postgresql-admin-credentials
          key: db.user
    password:
      valueFrom:
        secretKeyRef:
          name: postgresql-admin-credentials
          key: db.password

  modules:
    createDatabase:
      enabled: true
    migrateDatabase:
      enabled: true
    createImporters:
      enabled: true
      importers:
        redhat-sboms:
          sbom:
            description: All Red Hat SBOMs
            period: 1d
            source: https://access.redhat.com/security/data/sbom/beta/
            keys:
              - https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4
            disabled: true
            fetchRetries: 50
        redhat-csaf:
          csaf:
            description: All Red Hat CSAF data
            period: 1d
            source: redhat.com
            disabled: true
            fetchRetries: 50
        cve:
          cve:
            description: CVE list v5
            period: 1d
            source: https://github.com/CVEProject/cvelistV5
            disabled: false
        osv-github:
          osv:
            description: GitHub Advisory Database
            period: 1d
            source: https://github.com/github/advisory-database
            path: advisories
            disabled: false
            
  oidc:
    issuerUrl: https://sso.apps.ocp.aws.ispworld.at/realms/openshift
    clients:
      frontend:
        clientId: openshift
      cli:
        clientId: openshift
        clientSecret:
          valueFrom:
            secretKeyRef:
              name: oidc-cli
              key: client-secret

  #$schema: "charts/trustify/values.schema.json"

  # appDomain: apps.ocp.aws.ispworld.at
  # tracing: {}

  # modules:
  #   createImporters:
  #     enabled: true
  #     importers:
  #       redhat-sboms:
  #         sbom:
  #           description: All Red Hat SBOMs
  #           period: 1d
  #           source: https://access.redhat.com/security/data/sbom/beta/
  #           keys:
  #             - https://access.redhat.com/security/data/97f5eac4.txt#77E79ABE93673533ED09EBE2DCE3823597F5EAC4
  #           disabled: true
  #           fetchRetries: 50
  #       redhat-csaf:
  #         csaf:
  #           description: All Red Hat CSAF data
  #           period: 1d
  #           source: redhat.com
  #           disabled: true
  #           fetchRetries: 50
  #       cve:
  #         cve:
  #           description: CVE list v5
  #           period: 1d
  #           source: https://github.com/CVEProject/cvelistV5
  #           disabled: false
  #       osv-github:
  #         osv:
  #           description: GitHub Advisory Database
  #           period: 1d
  #           source: https://github.com/github/advisory-database
  #           path: advisories
  #           disabled: false