---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  encryptedData:
    access-key-id: AgCU10Ge9XZTQkGqB0Gyi1EB1+c4BhFk2t6VjWSHGl9Az59KND+hoEcgR1EUyHThYeMUhcalaroU0jdg5HE7CUZnsYDEzWDeyawTe1q36X13mD1t90pbnhneKwQHM03/rZZ6ygFPSdQ5C3ob4NWTObuiD+/EEPg7QarQF3FLl9VYdG+MPTwPE2xZwI7//tK0BBxnBs3DileZAH52bGVlNsCAjmg2jUds/5TiBog84346zC4+QHwXieZdwyzghFVerh0VMGeVtqyV1wrN2dsGx8TN1OGPIfkKd6DCd7e02L/bewwPcY42/ekExEqviSeJdlJBebsZRb8MKRHQL6tBboc7r6ApPhojEOchymqQg0sOIqWImZqkTfwXD1kPbhMcfsTTAFMYptvfjzoeD1dutR5GH7NAYa+kC22Dh/CS6lD26XY+tS/XcoVpGSMBgrAHFvypvPSNxYXeHBVZ6CuTJ6zlziVMf7Kkd+ma0vtJKjELIDfjG7ltE4ae0N1gkyoqxnJz+COqjsFOXpPY7tY9GUXCvIeR3ta+L/iLRWAXqKq92xsPtkAusFvp3Oi3hXl4PE59jfiYyXR4BTMGavyhZEfrxCmcKN9xWaZXKgoxgZRsLAVeUfwiIxy4IGyxmtXctdR1ubUgFoo47ntQ4VEWgCImZysGG3zc7G4x1NB1wA7XOAjm23RCNKkz3moFEedCtXMYFXANPkiqSLt1WyD2gPrsFC1GKA==
    secret-access-key: AgBFgMxzjXojQs3ha5lIM906jErdKxiwzs1NbLQHRQHQ69D3ituC57BtEK1WMloRyaOcWTwETT05zfc7TUYx4JfimTC4UypAkLJzlFCTz/tNiwC+NO4jeAwGMqiWgdXYwBX3F89m2LewBfKVEvlET3w3EHXsGiq/JbsNEQ7274xiq/qLix0dG3pGV8xbvzYomdIXQFnqnjMU/U8Opfk/urkoOkq+c6z7ljoo58CybI4gt1D0ze77Viw2AhQV3+hS7ke1yKyWLZS+r2D05TY9ski/VnV5ArXH/19mPQJEKs9VSK+7lhhf1JBu01jotqOrlBhTu14ab6FU1MREN2khrCtM8OYqvFfqZcX0YJvYoGRrUd64d15T0O3TxNDx+c/EHo/S43hnoIw1VFXs72M9nJ8AJEGMHqnMjmW+dLiDWeDCe9DhHbYRXHcG0tKF03vFCRj39n99FkXY4ncE4iKIf3coL7rBXbZ4GtrDERPHEoM/qwCpQz8AsnkgRTv5GMeTIyK8FZ5M53l5gQDveLGaxfAitJkirdG/P5/9e6ZI996FCrSGytVuZOsH8Vp4/iRYuCpnO5zf+BtJTaE73Fn2VaIvQBcaKzYTO2kWtdYj9RcMMpqdgH9KDaPKi0rYT4bXDMrWHRLSJ5yh+uTgTX6CnkoEJESMGDLX/7ogeLmNo+ovknV54A0qtF6u8avFM7h0N8wQTvwIcbba2IXyF9JOUI+UQv590y1GICOLkMkfBV+xhnmqWHzoM2Mb
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials-secret
      namespace: cert-manager