---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  encryptedData:
    access-key-id: AgB0ajPOqkGJKMIxnRm0lRcZFVfbwx5SP6i8tReZ/rYAhj1e4IXmcDPwQuJ0liQGYyG5PrHwCD0MgyvVFi5qJ66LG+vaYnSU7U3kPNm0ic4+s9xeT4ceGpV+cEccIjBfz+tbPBKUT/++qLPbvosiq6XdzBmLUoDXQNF/HGAx/knn2lfU+Xh6XhAvsPGJb2+4G+PAR8jzGcX2eAvEfPmmLUA0mYtAtW1m4myWMRgouKCbEIaQ3BKqrvygZ8GjddS7iesNKuo0ZDMQuZUEGXtg8zwpYZA/uDhEX/cT15d1+z3CAXCW4mu0YP/e/nRHcUj75gfJN9NXfM6f0B3Qt2pCIqesHTFJgBsgmeOe46XLSZE0MkLitQHrRKZJcJF1rNY3Xd0Kcg1TgqN7Z1PhMo3fK/r0OZWWGhooI9Vp0oUFSgJq40cfXnMAA9TRrfp3iwHpJ57ZfWBqpDb2MinAzdxYZAz43VIgoRuMshvsuL+ejBgSg93IbI+FE0uBUu8HjdrFTLy91hcYXw8O1GS7aQZ1cghVL+CC2u5q6SDbhs1JwX+rHqj44aZBYNGRfjG89DyrncO3p9NKw5CNz/q79Fw589AP9KGte/ThdepR2y25//owefE9qswzO0okTFnOmCblVNfBgiNczkYli+bB3ycyeIJfidDO/9GAdZlITgyQcNDOi7mZ6shG624Sadl3tPG/aOWps7BF512C9T/W1HRWv1pn5RqxLQ==
    secret-access-key: AgAMee+hlcc8TVqfrAm6jYMRxVxDYfnsDLf1eihKNai5rR7222lmm1dO8fheK6SVq/Sxcye70pvKsNwfcltdPiItGO4XNMoxkZWIxpyMSPwIRiqqmgIezvXPR1UGYIZ5zrpf/RfbPyPzdj1HWnIJnF41AzA38WoLUM1CXzs7xuloQkfQBrrBk9WkYLyGLioxUgq4gHXnLvBtwoqbnHfGUW1YhjdCp/C6rb6PiqmIMh7Hyz1spkwzWRq5/dILTB4Ff5V7gIMhjphhsiQe2fJs9fRK25DgAI/nVfu4tTDlQbpLi2qTMGK4VxanXVJvcnl3fPLz/1cXhXgPoeRu9wNJNXMRt9h8X82F6zUXemumfGsikUAeRqxauVo/CNAnuuPmwcZ9PmLn7O4DeXciLOfpsnrxU8ylNmi2qf4qbTBYZBwylX6mQIvRf82VFwl9m8UD9ZdEv8o8XN+x+SMoBT1saQ6dSOKQs1d8TO8GAa+URGbv3WpmN/z7Xq22QOCbf5XVrSHf5RsaLQZSG9PXDJKgmS70B9e8ah/Q4GpUP2t9gdZMj/7cSFP2Ss5KSefH4A8s98b5MquV6YKkWFLh0IclOf8asdAoXK2/HGO3JLWm2G4EBNZBzVUZ7hEExIOApI9dIW6IKokgz9OgyJ9QmknkNZbp3nfJHpFZGNpcNNAp1eXy2ObTBXi7RNHBRdjPsvYHYty+4NF4o+F5HzSHvlxya8Mary0BC/Y0ccV1MfwSnF849k5kwbP6Iu9i
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials-secret
      namespace: cert-manager
    type: Opaque