---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgBM7RLBxWfe9mpPAZWBBLDR3XFkodgrFl0fTZQHWULwtAjDAhHRCqgYXNyhyER8XwH4K2Sxc1FA7wNwWjtVwR87n8UlHbKqG+KEns3/PCOe29L2CrbflisXMw1yudmnaUTYzd5eVuKLTZ/miEDol+08SkCl8QpCpHk2z0uW1Ea9riB9NMeIjsMcQleWzC3BcwA2Z9WM4FsQ/9H7uuQ+2r40TTLRph+12MW7GTOCSwHRLP67CkZZtu8wQfpxU4nrbMp/3FWaEA3zan7j8clZpy5SfEMgJthvMdkxQ7Jw3UtcvnG/2Tu7WX7MtVkaTGaoChe92X0RJevBS+0iUUxJx39PDwq/IhEyA3q/Y9bWZiLfRnTCU0F7P5F/QEQ58C9viES/pf9Jg6btAbBlxAM28XHvcej9okjN6n6zJmI1PkRrBpT3iJlzIKRVHH8VIfryVd3orqtZKRZcEd2YqWQsocgmD/DTkYYm2uOETMikk/dkKjiV/Wgblaq2dXmajDP5W1702/vf/dq1RUEF194Kc6iakSK2GPTBDU8NqpnkyTD0S/e9SIfSfyDyPOGu3ksuv9v30KscaMHlb7QWD9wEkQapbVsrLitVTh4ecMNDfWPs6erx6vip3V3Wi9ku0cSLeb3oD4fzreWzrPSo4li2i9hCoTPnRd6xrust0ZNcSTVTgyjJX2F0MgD5CTOjg57Ebbvp4GxlZ2jh8AIL0dhu9zEm0YXOtw==
    secret-access-key: AgAokEsb8WHn8qMLY/RZP2bNRAN29t15xIIIr1K4fkeUHr8JnDgI7rghKad+3FzI77En+t4E6hXu6zRLybSJTaBNU8a3iY+ZpY7k8z4IOfIUa5FSFcsyoFiyiJPfdAdYzqRPFYELBVofcDBoVxXcfaevdHEv1cgCaoij/Dku1qeziNvAG6t5FBrVgDeF16PZLPpGj+VzGAT8vtLJPmGpJeoc0RcqRYYAiyOVuvDyGfgTn6KuCK1+Cw9rlMCq4ZgW8keX54n15LP4nbukV8JfiFHCquNN5qainweQxOS/Ck2LswKJjwkQLS1JXPSwHwY4cnGYxxu98wlA5DTmd3xIfkShmZKm4VIEYV/f1m4/q+9wKihkLjWTHeqtzvm9ktkDiRUZHNrnpXqJY8QtrjiAFUJPQVtnbERecWiDZRpUvlVzBtQQfwm5+CZlHu/jM4qNvF5TCbduFAR/CpRldvT/+/TA2wP2I6L/cqWGPflBrpUREissfhR+/g0MI1dKqWjB0CdmwQPu0JhCAl8GJZQNEYp/Vu5UYyVzqi/Ran1uITr7j7ZNY+reJUmVjZgR3X0fwIcwRqoZgMuVXMsYVtJOIkTAwJR9JP6KEqbzhKl1tlxqOfYr6M2K6KelJJmJQQ420TGvUTor1rP93LA7zxLV+7IQJDezexqqbr/R0lWrO05kLVhg4x/pwPq8tw/snCDsoakECZxz67iRtOu5vewYjbD02eBeBybI+5VC9ijJyEcjN59+z/IGj/gn
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials-secret
      namespace: cert-manager