---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-route53-credentials-secret
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgCfy6kcCbUwJm8lQlgogiujjwlEmS09NB4e7VXB4ySmIndx14iOVMDgYH31897biPFSyR231c9aeYC839rZhWBVzGF6DD7DZ1It9aKhDEWGsNqBtpvTXBKy2o1Y62BLpFup4q0St87ehj/CmqLhAzU3bkfjcsDW/ZKSyfMI9BV9/EQ+c204Nx+vOLc/j2r8P43xITyhzg8qHg+zB/Bs50UqdD+lK1qlKCZy8kOh6oZ5oavKZtlRWhs85wSQOMAf/3d07k1hkIslLx5wLcqC/sQcxk9Gq5fJyVxuMBHyaMbjDy7XuT4y32lkTzMKNw4pllcR/Q660m5muB/Gb46X4qguoQ8JO72yR4WaVWQnLTni32Nj01lfDMGwomK2m1830axVz9wzwcMSsZOrbyAmb3yvY3mHfgvJJ7nIB91rz/JCRQIeQcSEzmeOvv8hGxsoqO//3//BNaM/r6rsRUUUzV/XszvDEycU6rhSUGJDq+GGYLvP7nRG1NnETP0d6Vo7ZTkOrKq8WUkOKtZhw9m+WayUedZCMsXmhypGirC80ZpHxQz3hAdTh21fFpRPTrbWKXdxD2kvV3uQ1mRvlNcdnMjO6GxdMR/LpI6qIO+qVNdqgMmJ+gkyDD3DK+tBne6FEMxdNq3H+Ef9npfsIir3vHkp/y78S83CKSrqY+hqWNXDa4c6DfwTDMi2rPNrSzLMTu/PTz/dv5em6z+b60E8ptuUBRTlVQ==
    secret-access-key: AgArsykG+RKJ46f0+Yu+w9M3Gtli5G2nxv/22JCzg848KxlQYlK/zac50FxeS0I9IT3cmFQNx/f3sEEDnWO4nwxFmPowMrep2p1KyeaY4QD3fiDP2X8SdGr2CmoXVOTSUeM8vAYi4EMKVEwmiyyME9HxPckhY9lBUfIMs9ZClLq63ARZoWNSyroRiwnvFy6lY6igPxyFli26m0t75QDVg21xS9kIEsEFslAY1QWSyHQa2PgdZ2CCFrnoVzSzzFal+X66ojWnqZsK9zKBAeWCzf6k/v+Hr3JPbeCe30wb3abgUqYUcD8FAEA4LUTLH01S8dFb+P6V06IPqRaKnTr+dr7aSsKvoqtk3bZ0rtLWC6T2Qf+Lyf1BiHnB4WnPEKA7sjvfopRwV3Uw/6rikfYimOm4IT1IMUDBnc1KeyFPu4gktNFTeja9VzCrPKJZhDgCJOkWflt+CZnFYnPAUc8+Z+BdPnGP0TiYPIK0d4z/ykbZ04HcyH5x9qMp4JhFmBkTxnWZ6IaJGXlndRvrZPiqPOR+PUS2/s6TtAYApkkeowgh6DB4oPt+7234b+nlDDtE94D4oqif1BD63YQhp1dDMRotW0eCr5ToHPnGygTzzLZnhH6/Fpsu6vXWEL+CjhvxjzVBdC1++Wkd47+LsiuV0IWT9Gvq92ub+1W/oe0+gwk7KU9oIUxHUym6sU5Wtxcz5gd0hpjuYKl+gXHHJ3WDpyTFBwcg+mka+CiXkKSqcSb184GbNd/h03+1
  template:
    metadata:
      creationTimestamp: null
      name: prod-route53-credentials-secret
      namespace: cert-manager
