{{- if eq ( .Values.multicluster_observability.enabled | toString) "true" }}
{{- with .Values.multicluster_observability }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-s3-secret-sa
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 3 | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
