{{- if eq ( .Values.multicluster_observability.enabled | toString) "true" }}
{{- with .Values.multicluster_observability }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-s3-secret-crb-{{ .namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 3 | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: create-s3-secret-sa
    namespace: {{ .namespace }}
{{- end }}
{{- end }}
