{{- if eq ( .Values.multicluster_observability.enabled | toString) "true" }}
{{- with .Values.multicluster_observability }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-s3-bucket-secret
  namespace:  {{ .namespace }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default "10" | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      name: create-s3-secret
    spec:
      containers:
        - name: create-s3-secret
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash

              # Sleeping before starting with the work, to be sure the bucket has been created.
              SLEEPER_TMP=0

              printf "Waiting 20 seconds before I start with the generation of the configuration\n"
             
              while [[ $SLEEPER_TMP -le "20" ]]; do
                echo -n "."
                sleep 1
                SLEEPER_TMP=$(($SLEEPER_TMP+1))
              done

              printf "\nTrying to create the required ACM secret file\n"

              bucket_user=`cat /tmp/bucket-secret/AWS_ACCESS_KEY_ID`

              bucket_secret=`cat /tmp/bucket-secret/AWS_SECRET_ACCESS_KEY`

              bucket_name=`cat /tmp/s3-bucket/BUCKET_NAME`

              bucket_host=`cat /tmp/s3-bucket/BUCKET_HOST`

              bucket_region=`cat /tmp/s3-bucket/BUCKET_REGION`

              oc create secret generic {{ .s3_secretname }} --from-literal thanos.yaml="type: s3
              config:
                bucket: ${bucket_name}
                endpoint: ${bucket_host}
                insecure: true
                access_key: ${bucket_user}
                secret_key: ${bucket_secret}" --type=Opaque

              printf "\nSecret {{ .s3_secretname }} has been created\n"
          volumeMounts:
            - name: bucket-secret
              mountPath: "/tmp/bucket-secret"
              readOnly: true
            - name: s3-bucket
              mountPath: /tmp/s3-bucket
      volumes:
        - name: bucket-secret
          secret:
            secretName: {{ .bucket.name }}
        - name: s3-bucket
          configMap:
            name: {{ .bucket.name }}
      restartPolicy: Never
      serviceAccountName: create-s3-secret-sa
{{- end }}
{{- end }}
