apiVersion: v2
name: setup-acs
description: Deploys Advanced Cluster Managment (ACM) on target cluster.
version: 1.0.0
dependencies:
  - name: rhacm-setup
    version: ~1.0.0
    repository: https://charts.stderr.at/
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
keywords:
  - acs
  - security
