{{- if eq (.Values.tempostack.enabled | toString) "true" }}
{{- with .Values.tempostack }}
---
apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack 
metadata:
  name: {{ .name }}
  namespace: {{ .namespace.name }}
  annotations:
    {{- include "tpl.additionalAnnotations" .additionalAnnotations | nindent 4 }}
  labels:
    {{- include "tpl.labels" $ | nindent 4 }}
    {{- include "tpl.additionalLabels" .additionalLabels | nindent 4 }}
spec: 
  storage: 
    secret: 
      name: tempo-s3
      type: s3
  storageSize: 500Gi 
  resources: 
    total:
      limits:
        memory: 2Gi
        cpu: 2000m
  tenants:
    mode: openshift 
    authentication: 
      - tenantName: dev 
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa" 
      - tenantName: prod
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfb"
  template:
    gateway:
      enabled: true 
    queryFrontend:
      jaegerQuery:
        enabled: true 
{{- end }}
{{- end }}