apiVersion: v2
name: setup-tempo-operator
description: Installs and configures the Tempo Operator (distributed tracing). This Operator will require a S3 storage, which can be installed and provided using ODF and available Helm Sub-Charts.
version: 1.0.0
dependencies:
  - name: tpl
    version: ~1.0.0
    repository: https://charts.stderr.at/
  - name: helper-operator
    version: ~1.0.18
    repository: https://charts.stderr.at/
  - name: helper-status-checker
    version: ~4.0.0
    repository: https://charts.stderr.at/
    condition: helper-status-checker.enabled
  - name: helper-loki-bucket-secret
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: helper-loki-bucket-secret.enabled
  - name: helper-objectstore
    version: ~1.0.0
    repository: https://charts.stderr.at/
    condition: helper-objectstore.enabled
maintainers:
  - name: tjungbauer
    email: tjungbau@redhat.com
    url: https://blog.stderr.at/
sources:
  - https://github.com/tjungbauer/helm-charts
  - https://charts.stderr.at/
  - https://github.com/tjungbauer/openshift-clusterconfig-gitops
home: https://github.com/tjungbauer/openshift-clusterconfig-gitops/tree/main/clusters/management-cluster/setup-tempo-operator
keywords:
  - tracing
  - tempo
